Tasks inside the content of other macros are not assigned an ID #34
xwikisas/application-task pull request #35
Opened 2023-06-15 12:39 UTC by trrenty

To solve this issue, I had to parse the content of the macros that supported wiki syntax.

2023-06-16 07:53 UTC, mflorea requested changes
Would be nice to separate / extract the generic (utility) code from the code that is specific to the Task Application domain.

2023-06-16 07:53 UTC, mflorea commented on application-task-default/src/main/java/com/xwiki/task/internal/MacroDescriptorProcessor.java
> +private MacroManager macroManager;
Bad formatting.

2023-06-16 07:53 UTC, mflorea commented on application-task-default/src/main/java/com/xwiki/task/internal/MacroDescriptorProcessor.java
> +
Unneeded empty lines.

2023-06-16 07:53 UTC, mflorea commented on application-task-default/src/main/java/com/xwiki/task/internal/MacroDescriptorProcessor.java
> +public class MacroDescriptorProcessor
I'd rather make this a generic macro utility component (e.g. ``MacroUtils``), and move here ``updateMacroContent`` and possibly ``getTaskContentXDOM`` and ``renderTaskContent`` (of course, after renaming them).

2023-06-19 20:57 UTC, trrenty commented on application-task-default/src/main/java/com/xwiki/task/internal/MacroBlockVisitor.java
> +public class MacroBlockVisitor
What about `MacroBlockFinder`. The way i see it, this is it's purpose, to find macro blocks. Other variant might be `XDOMTraverser`. WDYT

2023-06-20 04:58 UTC, mflorea approved these changes
Looks good.

2023-06-20 04:58 UTC, mflorea commented on application-task-default/src/main/java/com/xwiki/task/internal/TaskXDOMProcessor.java
> +    private MacroBlockFinder blockVisitor;
```suggestion
    private MacroBlockFinder macroBlockFinder;
```

2023-06-20 07:42 UTC, merged